# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeplace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coffee_places'),
        ),
        migrations.AlterField(
            model_name='coffeeplace',
            name='name',
            field=models.CharField(blank=True, default='', max_length=256),
            preserve_default=False,
        ),
    ]
