# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 09:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coffee_places', '0003_remove_coffeeplace_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited', models.NullBooleanField()),
                ('going', models.NullBooleanField()),
                ('later', models.NullBooleanField()),
                ('never', models.NullBooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='coffeeplace',
            name='category',
            field=models.CharField(blank=True, default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersuggestion',
            name='cofeeplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_places.CoffeePlace'),
        ),
        migrations.AddField(
            model_name='usersuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
