# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_places', '0004_auto_20170310_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersuggestion',
            old_name='cofeeplace',
            new_name='coffeeplace',
        ),
    ]
