# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 15:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_places', '0005_auto_20170310_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL),
        ),
    ]
