# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 09:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coffee_places', '0006_auto_20170310_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited', models.NullBooleanField()),
                ('going', models.NullBooleanField()),
                ('later', models.NullBooleanField()),
                ('never', models.NullBooleanField()),
                ('coffee_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='coffee_places.CoffeePlace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usersuggestion',
            name='coffeeplace',
        ),
        migrations.RemoveField(
            model_name='usersuggestion',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserSuggestion',
        ),
    ]
