# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 09:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coffee_places', '0007_auto_20170313_0916'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='suggestion',
            unique_together=set([('user', 'coffee_place')]),
        ),
    ]
