# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_places', '0008_auto_20170313_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeplace',
            name='city',
            field=models.CharField(default='Львів', max_length=256),
        ),
        migrations.AddField(
            model_name='coffeeplace',
            name='uid',
            field=models.CharField(default='', max_length=256, unique=True),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='modified',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
