# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_places', '0009_auto_20170313_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeplace',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
