# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_places', '0010_coffeeplace_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeplace',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coffeeplace',
            name='tips_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
