# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_places', '0011_auto_20170315_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='later',
            new_name='never_show',
        ),
        migrations.RenameField(
            model_name='suggestion',
            old_name='never',
            new_name='show_later',
        ),
    ]
