# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_places', '0012_auto_20170316_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
