# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 15:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_places', '0013_auto_20170316_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 3, 16, 15, 6, 50, 212627, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 3, 16, 15, 6, 59, 624481, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
