# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_places', '0014_auto_20170316_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeplace',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coffeeplace',
            name='foursquare_id',
            field=models.CharField(default='', max_length=256),
        ),
    ]
