# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-01 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_places', '0016_auto_20170711_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='visited',
        ),
        migrations.AddField(
            model_name='visit',
            name='suggestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='coffee_places.Suggestion'),
        ),
    ]
